#! /bin/sh

wmname LG3D
nitrogen --restore &
picom &
flameshot &
xautocfg &
numlockx & 
clipcatd &
xsetroot -cursor_name left_ptr

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10
bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color "#52b788"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a thunar state=floating
bspc rule -a Screenkey manage=off
# ----- set keyboard Layout ----- #
setxkbmap -layout us,ru
setxkbmap -option 'grp:win_space_toggle'
